In [16]:
#Import Library
import pandas as pd

In [24]:
#Load Dataset
df = pd.read_csv("ids.csv")

In [18]:
#Show Dataset Shape/Structure
df.shape

(488115, 80)

In [19]:
#Show First Few Rows
df.head()

,Unnamed: 0,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,53,62171,2,2,78,164,39,39,39.00,...,32,0.00000,0.00000,0,0,0.0,0.000000,0,0,BENIGN
1,1,2710,48,2,0,4,0,2,2,2.00,...,24,0.00000,0.00000,0,0,0.0,0.000000,0,0,Infiltration
2,2,443,4792909,5,1,135,46,46,6,27.00,...,20,0.00000,0.00000,0,0,0.0,0.000000,0,0,BENIGN
3,3,80,115596470,75,82,342,118155,342,0,4.56,...,32,22092.63636,22835.59127,90944,14999,10000000.0,2701.650839,10000000,9997164,BENIGN
4,4,2910,14,2,2,4,12,2,2,2.00,...,24,0.00000,0.00000,0,0,0.0,0.000000,0,0,BENIGN

In [20]:
#Show Columns
df.columns

Index(['Unnamed: 0', 'Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags',
       'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length',
       'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s',
       'Min Packet Length', 'Max Packet Length', 'Packet Length Mean',
       'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count',
       'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio',
       'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size',
       'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk',
       'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes',
       'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward',
       'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean',
       'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [21]:
#Show Data Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488115 entries, 0 to 488114
Data columns (total 80 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   488115 non-null  int64
 1   Destination Port             488115 non-null  int64
 2   Flow Duration                488115 non-null  int64
 3   Total Fwd Packets            488115 non-null  int64
 4   Total Backward Packets       488115 non-null  int64
 5   Total Length of Fwd Packets  488115 non-null  int64
 6   Total Length of Bwd Packets  488115 non-null  int64
 7   Fwd Packet Length Max        488115 non-null  int64
 8   Fwd Packet Length Min        488115 non-null  int64
 9   Fwd Packet Length Mean       488115 non-null  float64
 10  Fwd Packet Length Std        488115 non-null  float64
 11  Bwd Packet Length Max        488115 non-null  int64
 12  Bwd Packet Length Min        488115 non-null  int64
 13  Bwd Packet Length Mean       488115 non-null  float64
 14  Bwd Packet Length Std        488115 non-null  float64
 15  Flow Bytes/s                 488079 non-null  float64
 16  Flow Packets/s               488115 non-null  float64
 17  Flow IAT Mean                488115 non-null  float64
 18  Flow IAT Std                 488115 non-null  float64
 19  Flow IAT Max                 488115 non-null  int64
 20  Flow IAT Min                 488115 non-null  int64
 21  Fwd IAT Total                488115 non-null  int64
 22  Fwd IAT Mean                 488115 non-null  float64
 23  Fwd IAT Std                  488115 non-null  float64
 24  Fwd IAT Max                  488115 non-null  int64
 25  Fwd IAT Min                  488115 non-null  int64
 26  Bwd IAT Total                488115 non-null  int64
 27  Bwd IAT Mean                 488115 non-null  float64
 28  Bwd IAT Std                  488115 non-null  float64
 29  Bwd IAT Max                  488115 non-null  int64
 30  Bwd IAT Min                  488115 non-null  int64
 31  Fwd PSH Flags                488115 non-null  int64
 32  Bwd PSH Flags                488115 non-null  int64
 33  Fwd URG Flags                488115 non-null  int64
 34  Bwd URG Flags                488115 non-null  int64
 35  Fwd Header Length            488115 non-null  int64
 36  Bwd Header Length            488115 non-null  int64
 37  Fwd Packets/s                488115 non-null  float64
 38  Bwd Packets/s                488115 non-null  float64
 39  Min Packet Length            488115 non-null  int64
 40  Max Packet Length            488115 non-null  int64
 41  Packet Length Mean           488115 non-null  float64
 42  Packet Length Std            488115 non-null  float64
 43  Packet Length Variance       488115 non-null  float64
 44  FIN Flag Count               488115 non-null  int64
 45  SYN Flag Count               488115 non-null  int64
 46  RST Flag Count               488115 non-null  int64
 47  PSH Flag Count               488115 non-null  int64
 48  ACK Flag Count               488115 non-null  int64
 49  URG Flag Count               488115 non-null  int64
 50  CWE Flag Count               488115 non-null  int64
 51  ECE Flag Count               488115 non-null  int64
 52  Down/Up Ratio                488115 non-null  int64
 53  Average Packet Size          488115 non-null  float64
 54  Avg Fwd Segment Size         488115 non-null  float64
 55  Avg Bwd Segment Size         488115 non-null  float64
 56  Fwd Header Length.1          488115 non-null  int64
 57  Fwd Avg Bytes/Bulk           488115 non-null  int64
 58  Fwd Avg Packets/Bulk         488115 non-null  int64
 59  Fwd Avg Bulk Rate            488115 non-null  int64
 60  Bwd Avg Bytes/Bulk           488115 non-null  int64
 61  Bwd Avg Packets/Bulk         488115 non-null  int64
 62  Bwd Avg Bulk Rate            488115 non-null  int64
 63  Subflow Fwd Packets          488115 non-null  int64
 64  Subflow Fwd Bytes            488115 non-null  int64
 65  Subflow Bwd Packets          488115 non-null  int64
 66  Subflow Bwd Bytes            488115 non-null  int64
 67  Init_Win_bytes_forward       488115 non-null  int64
 68  Init_Win_bytes_backward      488115 non-null  int64
 69  act_data_pkt_fwd             488115 non-null  int64
 70  min_seg_size_forward         488115 non-null  int64
 71  Active Mean                  488115 non-null  float64
 72  Active Std                   488115 non-null  float64
 73  Active Max                   488115 non-null  int64
 74  Active Min                   488115 non-null  int64
 75  Idle Mean                    488115 non-null  float64
 76  Idle Std                     488115 non-null  float64
 77  Idle Max                     488115 non-null  int64
 78  Idle Min                     488115 non-null  int64
 79  Label                        488115 non-null  object
dtypes: float64(24), int64(55), object(1)
memory usage: 297.9+ MB

In [22]:
#Show Label Distribution
df['Label'].value_counts()

Label
BENIGN          288566
Infiltration    199549
Name: count, dtype: int64

In [23]:
#Last 50 Records
df.tail(50)

,Unnamed: 0,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
488065,488065,53,70591,2,2,66,194,33,33,33.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488066,488066,443,5572560,8,6,386,5205,205,0,48.250000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488067,488067,3013,49,2,0,4,0,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488068,488068,53,122130,2,2,80,272,40,40,40.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488069,488069,53,98106274,2,2,114,211,58,56,57.000000,...,20,30943.00000,0.00000,30943,30943,9.800000e+07,0.00000,98000000,98000000,Infiltration
488070,488070,53,506,1,1,53,113,53,53,53.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488071,488071,53,3957631,2,2,120,260,79,41,60.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488072,488072,9102,2,2,0,4,0,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488073,488073,2135,111,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488074,488074,1048,49,2,0,4,0,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488075,488075,54240,55,1,1,6,6,6,6,6.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488076,488076,1049,73,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488077,488077,443,4,2,0,12,0,6,6,6.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488078,488078,53,172,2,2,80,112,40,40,40.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488079,488079,443,79063,1,2,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488080,488080,51425,4,2,0,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488081,488081,5120,85,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488082,488082,39930,4,2,0,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488083,488083,443,5871633,7,4,635,168,517,0,90.714286,...,32,150944.00000,0.00000,150944,150944,5.720685e+06,0.00000,5720685,5720685,BENIGN
488084,488084,10616,99,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488085,488085,443,115338719,22,18,1317,7539,864,0,59.863636,...,20,84994.45455,93143.49644,365777,56220,9.992959e+06,27637.53213,10000000,9910557,BENIGN
488086,488086,60928,52,1,1,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488087,488087,22,1340965,41,42,2728,6634,456,0,66.536585,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488088,488088,443,1142446,78,107,997,227837,517,0,12.782051,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488089,488089,53,67977,2,2,70,130,35,35,35.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488090,488090,53,32534951,2,2,130,297,79,51,65.000000,...,32,475.00000,0.00000,475,475,3.250000e+07,0.00000,32500000,32500000,Infiltration
488091,488091,53,31361,2,2,70,198,35,35,35.000000,...,40,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488092,488092,53,228451,2,2,62,240,31,31,31.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488093,488093,53,216,2,2,78,160,39,39,39.000000,...,40,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488094,488094,6302,47740,2,0,6,0,6,0,3.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488095,488095,53,210,2,2,70,130,35,35,35.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488096,488096,443,5322619,5,5,3471,1132,1993,6,694.200000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488097,488097,53,118556,2,2,76,300,38,38,38.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488098,488098,389,69,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488099,488099,5405,72,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488100,488100,53,206842,1,1,48,142,48,48,48.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488101,488101,8402,49,2,0,4,0,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488102,488102,21,72,1,2,6,12,6,6,6.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488103,488103,43118,69,1,1,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488104,488104,53,48546,2,2,70,102,35,35,35.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488105,488105,49848,19,2,2,12,4,6,6,6.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488106,488106,443,31143,4,1,190,0,190,0,47.500000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488107,488107,53,51160,1,1,43,113,43,43,43.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488108,488108,80,23207,2,0,12,0,6,6,6.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488109,488109,80,5149971,3,1,0,0,0,0,0.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488110,488110,53,238,2,2,86,228,43,43,43.000000,...,32,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488111,488111,8899,3,2,0,4,0,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,Infiltration
488112,488112,53,250,2,2,82,206,41,41,41.000000,...,20,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN
488113,488113,53,70581019,2,2,117,231,66,51,58.500000,...,32,41306.00000,0.00000,41306,41306,7.030000e+07,0.00000,70300000,70300000,BENIGN
488114,488114,5679,121,2,2,4,12,2,2,2.000000,...,24,0.00000,0.00000,0,0,0.000000e+00,0.00000,0,0,BENIGN